#!/bin/bash

echo "Changing directory to /media/$(whoami)/backup"
cd /media/$(whoami)/backup

echo "Making directory backup_$(date +"%Y%m%d")"
mkdir backup_$(date +"%Y%m%d")

echo "Changing directory to /media/$(whoami)/backup/backup_$(date +"%Y%m%d")"
cd backup_$(date +"%Y%m%d")

echo ""
echo "Backup..."

echo "Copying ~/Dokumenty"
cp -Rv ~/Dokumenty/ .

echo "Copying ~/Projekty"
cp -Rv ~/Projekty/ .

echo "Copying ~/.config"
cp -Rv ~/.config/ .

echo "Copying ~/.fonts"
cp -Rv ~/.fonts/ .

echo "Copying ~/.vpn"
cp -Rv ~/.vpn/ .

echo "Copying ~/.vim"
cp -Rv ~/.vim/ .

echo "Copying ~/.ssh"
cp -Rv ~/.ssh/ .

echo "Copying ~/.aliases"
cp ~/.aliases .

echo "Copying ~/.gitconfig"
cp ~/.gitconfig .

echo "Copying ~/.gitignore_global"
cp ~/.gitignore_global .

echo "Copying ~/.npmrc"
cp ~/.npmrc .

echo "Copying ~/.tmux.conf"
cp ~/.tmux.conf .

echo "Copying ~/.oh-my-zsh/themes/toffi9.zsh-theme"
cp -H ~/.toffi9.zsh-theme .

echo "Copying ~/.vimrc"
cp ~/.vimrc .

echo "Copying ~/.zshrc"
cp ~/.zshrc .

echo "Copying ~/.wallpaper.jpg"
cp ~/.wallpaper.jpg .
