#!/bin/bash

# Install xubuntu core from mini.iso (network installer) for latest ubuntu
# Check Install
# Don't autodetect keyboard, use polish
# fullname:toffi9 and user: toffi9
# don't encrypt home folder
# check Przewodnik - cały dysk i ustawienie szyfrowanego LVM
# don't do automatic updates
# check software:
#     * Xubuntu minimal installation
#     * Large selection of font packages
# everything else will be installed later

# RUN script below on your new installed xubuntu core system
# ------------------------------------------------------------------

# Update and upgrade system
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install whiptail vim wget -y

# swap capslock with esc
/usr/bin/setxkbmap -option "caps:swapescape"

# config grub for not showing splash screen
whiptail --title "Don't showing splash screen" \
  --msgbox "Comment out this line:

  # GRUB_CMDLINE_LINUX_DEFAULT=\"splash quiet\"

Add to file this lanes:

  GRUB_GFXMODE=1440x900
  GRUB_GFXPAYLOAD_LINUX=1440x900" 18 78

sudo vim /etc/default/grub
sudo update-grub2

# SSD tweaks
# http://www.leniwiec.org/2014/04/20/kilka-porad-dotycz%C4%85cych-u%C5%BCytkowania-dysk%C3%B3w-ssd-w-ubuntu-linuxie/
echo "vm.swappiness = 20" | sudo tee -a /etc/sysctl.conf
echo "vm.vfs_cache_pressure=50" | sudo tee -a /etc/sysctl.conf

whiptail --title "Add noatime" \
  --msgbox "
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
/dev/mapper/dell--vg-root /               ext4    noatime,errors=remount-ro 0       1" 20 90
sudo vim /etc/fstab

# Turn on TRIMming
whiptail --title "Turn on rc.local fstrim" \
  --msgbox "
#!/bin/sh -e
fstrim -v /
exit 0
" 10 70
sudo vim /etc/rc.local
sudo chmod +x /etc/rc.local
sudo service rc.local restart

# create my folder
cd $HOME
rm Muzyka/ Obrazy/ Publiczny/ Szablony/ Wideo/ -rf
mkdir Projekty

sudo apt-get install -y apt-transport-https ca-certificates

# Sources.list
whiptail --title "Uncomment canonical partners" \
  --msgbox "" 10 70
sudo vim /etc/apt/sources.list

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886
sudo apt-key adv \
               --keyserver hkp://ha.pool.sks-keyservers.net:80 \
               --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

sudo add-apt-repository ppa:nilarimogard/webupd8
echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
sudo apt-add-repository ppa:ansible/ansible

echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" | sudo tee /etc/apt/sources.list.d/docker.list

sudo apt-get update

# Install kernel that works with docker
sudo apt-get install -y linux-image-extra-$(uname -r) linux-image-extra-virtual

# Install and config all needed software
sudo apt-get install -y \
  software-properties-common \
  htop \
  galculator \
  tmux \
  zsh \
  git \
  chromium-browser chromium-browser-l10n \
  firefox firefox-locale-pl \
  keepassx \
  xarchiver \
  thunar-archive-plugin \
  thunar-volman \
  redshift redshift-gtk \
  xfce4-timer-plugin \
  xfce4-taskmanager \
  zathura \
  gpicview \
  mousepad \
  filezilla \
  gimp gimp-data gimp-data-extras \
  virtualbox virtualbox-ext-pack \
  skype \
  mpv \
  kazam \
  pulseaudio-equalizer \
  spotify-client \
  grive \
  xclip \
  unzip \
  dnsmasq \
  ntfs-3g \
  network-manager-openvpn-gnome \
  network-manager-pptp-gnome \
  network-manager-ssh-gnome \
  network-manager-vpnc-gnome \
  ansible \
  docker-engine \
  ack-grep \
  python3-pip \
  zeal

# virtualenv
pip3 install virtualenvwrapper
whiptail --title "Notice" \
  --msgbox "
Remember to adjust source of virtualenvwrapper.sh in your .zshrc
" 10 70

# oh-my-zsh
cd $HOME
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

# ack
sudo dpkg-divert --local --divert /usr/bin/ack --rename --add /usr/bin/ack-grep
# menlo font
cd $HOME
mkdir -p .fonts/
cd .fonts/
wget https://github.com/abertsch/Menlo-for-Powerline/raw/master/Menlo%20for%20Powerline.ttf
cd $HOME
sudo fc-cache -f -v
# docker
sudo service docker start

# Copy all files
# grive
# cd $HOME/Dokumenty/ && grive -a && cd $HOME

# Config all stuff in xfce settings
# Shortcuts

# Exit with reboot
sudo reboot
exit 0
