#!/bin/bash

echo "Changing directory to ~/Projekty/dotfiles/"
cd ~/Projekty/dotfiles/

echo "Syncing..."
echo "Copying ~/.vim/UltiSnips/"
cp -R ~/.vim/UltiSnips/ .vim/

echo "Copying ~/.aliases"
cp ~/.aliases .

echo "Copying ~/.gitconfig"
cp ~/.gitconfig .

echo "Copying ~/.gitignore_global"
cp ~/.gitignore_global .

echo "Copying ~/.tmux.conf"
cp ~/.tmux.conf .

echo "Copying ~/.ctags"
cp ~/.ctags .

echo "Copying ~/.toffi9.zsh-theme"
cp -H ~/.toffi9.zsh-theme .

echo "Copying ~/.vimrc"
cp ~/.vimrc .

echo "Copying ~/.zshrc"
cp ~/.zshrc .

echo "Git commiting & pushing"
git add -A
git commit -m "dotfiles sync $(date +"%Y%m%d")"
git push origin master
